/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SucursalesRouteImport } from './routes/sucursales'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GarantiaRouteImport } from './routes/garantia'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EnviosRouteImport } from './routes/envios'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SucursalesIndexRouteImport } from './routes/sucursales.index'
import { Route as MetodosDePagoIndexRouteImport } from './routes/metodos-de-pago.index'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as SucursalesSlugRouteImport } from './routes/sucursales.$slug'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as MetodosDePagoTransferenciaRouteImport } from './routes/metodos-de-pago.transferencia'
import { Route as MetodosDePagoTarjetasRouteImport } from './routes/metodos-de-pago.tarjetas'
import { Route as MetodosDePagoEfectivoRouteImport } from './routes/metodos-de-pago.efectivo'
import { Route as CatalogoCategoriaIndexRouteImport } from './routes/catalogo.$categoria.index'
import { Route as CatalogoCategoriaSubcategoriaRouteImport } from './routes/catalogo.$categoria.$subcategoria'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SucursalesRoute = SucursalesRouteImport.update({
  id: '/sucursales',
  path: '/sucursales',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiaRoute = GarantiaRouteImport.update({
  id: '/garantia',
  path: '/garantia',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SucursalesIndexRoute = SucursalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SucursalesRoute,
} as any)
const MetodosDePagoIndexRoute = MetodosDePagoIndexRouteImport.update({
  id: '/metodos-de-pago/',
  path: '/metodos-de-pago/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const SucursalesSlugRoute = SucursalesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SucursalesRoute,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodosDePagoTransferenciaRoute =
  MetodosDePagoTransferenciaRouteImport.update({
    id: '/metodos-de-pago/transferencia',
    path: '/metodos-de-pago/transferencia',
    getParentRoute: () => rootRouteImport,
  } as any)
const MetodosDePagoTarjetasRoute = MetodosDePagoTarjetasRouteImport.update({
  id: '/metodos-de-pago/tarjetas',
  path: '/metodos-de-pago/tarjetas',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodosDePagoEfectivoRoute = MetodosDePagoEfectivoRouteImport.update({
  id: '/metodos-de-pago/efectivo',
  path: '/metodos-de-pago/efectivo',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoCategoriaIndexRoute = CatalogoCategoriaIndexRouteImport.update({
  id: '/catalogo/$categoria/',
  path: '/catalogo/$categoria/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoCategoriaSubcategoriaRoute =
  CatalogoCategoriaSubcategoriaRouteImport.update({
    id: '/catalogo/$categoria/$subcategoria',
    path: '/catalogo/$categoria/$subcategoria',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrito': typeof CarritoRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/faq': typeof FaqRoute
  '/garantia': typeof GarantiaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/sucursales': typeof SucursalesRouteWithChildren
  '/terminos': typeof TerminosRoute
  '/metodos-de-pago/efectivo': typeof MetodosDePagoEfectivoRoute
  '/metodos-de-pago/tarjetas': typeof MetodosDePagoTarjetasRoute
  '/metodos-de-pago/transferencia': typeof MetodosDePagoTransferenciaRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/sucursales/$slug': typeof SucursalesSlugRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/metodos-de-pago/': typeof MetodosDePagoIndexRoute
  '/sucursales/': typeof SucursalesIndexRoute
  '/catalogo/$categoria/$subcategoria': typeof CatalogoCategoriaSubcategoriaRoute
  '/catalogo/$categoria/': typeof CatalogoCategoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrito': typeof CarritoRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/faq': typeof FaqRoute
  '/garantia': typeof GarantiaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/metodos-de-pago/efectivo': typeof MetodosDePagoEfectivoRoute
  '/metodos-de-pago/tarjetas': typeof MetodosDePagoTarjetasRoute
  '/metodos-de-pago/transferencia': typeof MetodosDePagoTransferenciaRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/sucursales/$slug': typeof SucursalesSlugRoute
  '/catalogo': typeof CatalogoIndexRoute
  '/metodos-de-pago': typeof MetodosDePagoIndexRoute
  '/sucursales': typeof SucursalesIndexRoute
  '/catalogo/$categoria/$subcategoria': typeof CatalogoCategoriaSubcategoriaRoute
  '/catalogo/$categoria': typeof CatalogoCategoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrito': typeof CarritoRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/faq': typeof FaqRoute
  '/garantia': typeof GarantiaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/sucursales': typeof SucursalesRouteWithChildren
  '/terminos': typeof TerminosRoute
  '/metodos-de-pago/efectivo': typeof MetodosDePagoEfectivoRoute
  '/metodos-de-pago/tarjetas': typeof MetodosDePagoTarjetasRoute
  '/metodos-de-pago/transferencia': typeof MetodosDePagoTransferenciaRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/sucursales/$slug': typeof SucursalesSlugRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/metodos-de-pago/': typeof MetodosDePagoIndexRoute
  '/sucursales/': typeof SucursalesIndexRoute
  '/catalogo/$categoria/$subcategoria': typeof CatalogoCategoriaSubcategoriaRoute
  '/catalogo/$categoria/': typeof CatalogoCategoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrito'
    | '/contacto'
    | '/envios'
    | '/faq'
    | '/garantia'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/sucursales'
    | '/terminos'
    | '/metodos-de-pago/efectivo'
    | '/metodos-de-pago/tarjetas'
    | '/metodos-de-pago/transferencia'
    | '/producto/$slug'
    | '/sucursales/$slug'
    | '/catalogo/'
    | '/metodos-de-pago/'
    | '/sucursales/'
    | '/catalogo/$categoria/$subcategoria'
    | '/catalogo/$categoria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrito'
    | '/contacto'
    | '/envios'
    | '/faq'
    | '/garantia'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/terminos'
    | '/metodos-de-pago/efectivo'
    | '/metodos-de-pago/tarjetas'
    | '/metodos-de-pago/transferencia'
    | '/producto/$slug'
    | '/sucursales/$slug'
    | '/catalogo'
    | '/metodos-de-pago'
    | '/sucursales'
    | '/catalogo/$categoria/$subcategoria'
    | '/catalogo/$categoria'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrito'
    | '/contacto'
    | '/envios'
    | '/faq'
    | '/garantia'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/sucursales'
    | '/terminos'
    | '/metodos-de-pago/efectivo'
    | '/metodos-de-pago/tarjetas'
    | '/metodos-de-pago/transferencia'
    | '/producto/$slug'
    | '/sucursales/$slug'
    | '/catalogo/'
    | '/metodos-de-pago/'
    | '/sucursales/'
    | '/catalogo/$categoria/$subcategoria'
    | '/catalogo/$categoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CarritoRoute: typeof CarritoRoute
  ContactoRoute: typeof ContactoRoute
  EnviosRoute: typeof EnviosRoute
  FaqRoute: typeof FaqRoute
  GarantiaRoute: typeof GarantiaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  SucursalesRoute: typeof SucursalesRouteWithChildren
  TerminosRoute: typeof TerminosRoute
  MetodosDePagoEfectivoRoute: typeof MetodosDePagoEfectivoRoute
  MetodosDePagoTarjetasRoute: typeof MetodosDePagoTarjetasRoute
  MetodosDePagoTransferenciaRoute: typeof MetodosDePagoTransferenciaRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
  MetodosDePagoIndexRoute: typeof MetodosDePagoIndexRoute
  CatalogoCategoriaSubcategoriaRoute: typeof CatalogoCategoriaSubcategoriaRoute
  CatalogoCategoriaIndexRoute: typeof CatalogoCategoriaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucursales': {
      id: '/sucursales'
      path: '/sucursales'
      fullPath: '/sucursales'
      preLoaderRoute: typeof SucursalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantia': {
      id: '/garantia'
      path: '/garantia'
      fullPath: '/garantia'
      preLoaderRoute: typeof GarantiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucursales/': {
      id: '/sucursales/'
      path: '/'
      fullPath: '/sucursales/'
      preLoaderRoute: typeof SucursalesIndexRouteImport
      parentRoute: typeof SucursalesRoute
    }
    '/metodos-de-pago/': {
      id: '/metodos-de-pago/'
      path: '/metodos-de-pago'
      fullPath: '/metodos-de-pago/'
      preLoaderRoute: typeof MetodosDePagoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucursales/$slug': {
      id: '/sucursales/$slug'
      path: '/$slug'
      fullPath: '/sucursales/$slug'
      preLoaderRoute: typeof SucursalesSlugRouteImport
      parentRoute: typeof SucursalesRoute
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodos-de-pago/transferencia': {
      id: '/metodos-de-pago/transferencia'
      path: '/metodos-de-pago/transferencia'
      fullPath: '/metodos-de-pago/transferencia'
      preLoaderRoute: typeof MetodosDePagoTransferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodos-de-pago/tarjetas': {
      id: '/metodos-de-pago/tarjetas'
      path: '/metodos-de-pago/tarjetas'
      fullPath: '/metodos-de-pago/tarjetas'
      preLoaderRoute: typeof MetodosDePagoTarjetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodos-de-pago/efectivo': {
      id: '/metodos-de-pago/efectivo'
      path: '/metodos-de-pago/efectivo'
      fullPath: '/metodos-de-pago/efectivo'
      preLoaderRoute: typeof MetodosDePagoEfectivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$categoria/': {
      id: '/catalogo/$categoria/'
      path: '/catalogo/$categoria'
      fullPath: '/catalogo/$categoria/'
      preLoaderRoute: typeof CatalogoCategoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$categoria/$subcategoria': {
      id: '/catalogo/$categoria/$subcategoria'
      path: '/catalogo/$categoria/$subcategoria'
      fullPath: '/catalogo/$categoria/$subcategoria'
      preLoaderRoute: typeof CatalogoCategoriaSubcategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SucursalesRouteChildren {
  SucursalesSlugRoute: typeof SucursalesSlugRoute
  SucursalesIndexRoute: typeof SucursalesIndexRoute
}

const SucursalesRouteChildren: SucursalesRouteChildren = {
  SucursalesSlugRoute: SucursalesSlugRoute,
  SucursalesIndexRoute: SucursalesIndexRoute,
}

const SucursalesRouteWithChildren = SucursalesRoute._addFileChildren(
  SucursalesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CarritoRoute: CarritoRoute,
  ContactoRoute: ContactoRoute,
  EnviosRoute: EnviosRoute,
  FaqRoute: FaqRoute,
  GarantiaRoute: GarantiaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  SucursalesRoute: SucursalesRouteWithChildren,
  TerminosRoute: TerminosRoute,
  MetodosDePagoEfectivoRoute: MetodosDePagoEfectivoRoute,
  MetodosDePagoTarjetasRoute: MetodosDePagoTarjetasRoute,
  MetodosDePagoTransferenciaRoute: MetodosDePagoTransferenciaRoute,
  ProductoSlugRoute: ProductoSlugRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
  MetodosDePagoIndexRoute: MetodosDePagoIndexRoute,
  CatalogoCategoriaSubcategoriaRoute: CatalogoCategoriaSubcategoriaRoute,
  CatalogoCategoriaIndexRoute: CatalogoCategoriaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
